### ISSUE TITLE
If there's no preview, it should skip the preview modal

### ISSUE THREAD

**Issue by agilbert** [punkave/apostrophe-workflow#34]

**Comment by boutell** [comment]
I also think of it as a "confirm" modal...

**Comment by boutell** [comment]
Simply removing this modal as a step would not work well since it is (a) acting as a confirmation modal, (b) probably in need of a way to also see changes to schema fields, and (c) the place where you can click "history" instead to apply past commits. Maybe some of those things will be addressed in ways that allow us to remove this step when there is no preview but they have to be considered.

(Pieces do have a preview if a pieces page is available.)
