### ISSUE TITLE
committing a page change always ask to commit "undefined"

### ISSUE THREAD

**Issue by nofwayy** [punkave/apostrophe-workflow#62]
I think this is related to committing the global document when data.global is used at template level (even if no changes are made in data.global areas).  
The actual behavior is the following :  

commit a page => modal for reviewing "undefined" changes => modal to apply "undefined" changes to nodes => modal to review page changes => modal to apply page changes nodes

**Comment by boutell** [comment]
I have pushed a change to display the slug where no title is available. This correctly labels that doc as "global."

It is true that the modal for it appears even though it hasn't been modified. Right now this is essential because otherwise you have no way to access the commit history for global. But it's not an ideal user experience so we should keep thinking about less irritating ways to organize access to the commit modals for "related" resources like global or a piece that's edited on-page. Indeed, for a piece "show page" the situation might be reversed: the piece might make more sense as the primary thing you'd expect to get a modal for, while any content shared on the index page itself would be more of a secondary, less frequently updated thing.

I'll update the ticket re: handling commits of related resources like images etc. to also include thoughts about this.
